// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    CardProgress: typeof import('./components/CardProgress.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Drag: typeof import('./components/Drag.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/Table.vue')['default']
  }
}

export {}
